# Generated by Django 5.1.4 on 2025-01-04 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "extension",
                    models.CharField(max_length=10, verbose_name="Extension"),
                ),
                (
                    "width",
                    models.FloatField(blank=True, null=True, verbose_name="Width"),
                ),
                (
                    "height",
                    models.FloatField(blank=True, null=True, verbose_name="Height"),
                ),
                (
                    "number_of_channels",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Number of channels"
                    ),
                ),
                (
                    "number_of_pages",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Number of pages"
                    ),
                ),
            ],
            options={
                "verbose_name": "File Model",
                "verbose_name_plural": "Files Model",
                "db_table": "files_filemodel",
            },
        ),
    ]
